cobra:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint8
    pid: {p: 0.1, i: 0.0, d: 0.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint9
    pid: {p: 0.1, i: 0.0, d: 0.0}

  